workflows:
    # Android Build
    apk:
        name: React Native Android
        instance_type: mac_mini_m1
        max_build_duration: 120
        environment:
            groups: [APP_ENV]
            vars:
                EXPO_PROJECT_SLUG: "agrisa"
                GRADLE_OPTS: "-Xmx4096m -XX:MaxMetaspaceSize=1024m"
            node: 18
        cache:
            cache_paths: [$CM_BUILD_DIR/node_modules]
        scripts:
            - name: Install Dependencies
              script: |
                  curl -fsSL https://bun.sh/install | bash
                  export PATH="$HOME/.bun/bin:$PATH"
                  bun install && bun add -g @expo/cli

            - name: Build Android
              script: |
                  export PATH="$HOME/.bun/bin:$PATH"
                  [ -z "$EXPO_PUBLIC_API_URL" ] && echo "Missing API URL" && exit 1

                  export EXPO_PUBLIC_API_URL=$EXPO_PUBLIC_API_URL
                  export EXPO_PUBLIC_OPENMAPVN_KEY=$EXPO_PUBLIC_OPENMAPVN_KEY
                  export EXPO_PUBLIC_GEMINI_KEY=$EXPO_PUBLIC_GEMINI_KEY

                  # Prebuild
                  rm -rf android
                  bunx expo prebuild --platform android

                  # Copy google-services.json from repo to android/app
                  cp google-services.json android/app/

                  # Setup keystore
                  rm -f ~/.android/debug.keystore
                  keytool -genkeypair -alias androiddebugkey -keypass android \
                    -keystore ~/.android/debug.keystore -storepass android \
                    -dname 'CN=Android Debug,O=Android,C=US' -keyalg RSA \
                    -keysize 2048 -validity 10000

                  # Build APK
                  cd android
                  export GRADLE_OPTS="-Xmx4096m -XX:MaxMetaspaceSize=1024m"
                  ./gradlew clean assembleRelease --no-daemon --max-workers=2

                  # Rename APK
                  APK_PATH=$(find app/build/outputs/apk/release -name "*.apk" | head -1)
                  [ -f "$APK_PATH" ] && mv "$APK_PATH" app/build/outputs/apk/release/Agrisa.apk

        artifacts:
            - android/app/build/outputs/**/*.apk

        publishing:
            email:
                recipients:
                    [
                        nhancd909@gmail.com,
                        hgiap46@gmail.com,
                        laithinh1310@gmail.com,
                    ]
                notify:
                    success: true
                    failure: true

    # iOS Build
    ipa:
        name: React Native iOS IPA
        instance_type: mac_mini_m1
        max_build_duration: 120
        environment:
            groups: [APP_ENV]
            vars:
                BUNDLE_ID: "com.agrisa.Agrisa"
                APP_NAME: "Agrisa"
            node: 18
            xcode: latest
            cocoapods: default
        cache:
            cache_paths: [$CM_BUILD_DIR/node_modules]
        scripts:
            - name: Install Dependencies
              script: |
                  curl -fsSL https://bun.sh/install | bash
                  export PATH="$HOME/.bun/bin:$PATH"
                  bun install && bun add -g @expo/cli

            - name: Build iOS IPA
              script: |
                  export PATH="$HOME/.bun/bin:$PATH"
                  [ -z "$EXPO_PUBLIC_API_URL" ] && echo "Missing API URL" && exit 1

                  export EXPO_PUBLIC_API_URL=$EXPO_PUBLIC_API_URL
                  export EXPO_PUBLIC_OPENMAPVN_KEY=$EXPO_PUBLIC_OPENMAPVN_KEY
                  export EXPO_PUBLIC_GEMINI_KEY=$EXPO_PUBLIC_GEMINI_KEY

                  # Prebuild
                  rm -rf ios
                  bunx expo prebuild --platform ios

                  # Copy GoogleService-Info.plist from repo to ios/Agrisa
                  cp GoogleService-Info.plist ios/Agrisa/

                  # Install pods
                  cd ios && pod install && cd ..

                  # Build unsigned
                  xcodebuild \
                    -workspace ios/Agrisa.xcworkspace \
                    -scheme Agrisa \
                    -configuration Release \
                    -sdk iphoneos \
                    -derivedDataPath build \
                    CODE_SIGN_IDENTITY="" \
                    CODE_SIGNING_REQUIRED=NO \
                    CODE_SIGNING_ALLOWED=NO \
                    build

                  # Create IPA
                  APP_PATH=$(find build/Build/Products/Release-iphoneos -name "*.app" -type d | head -1)
                  mkdir -p output/Payload
                  cp -R "$APP_PATH" output/Payload/
                  cd output && zip -r Agrisa.ipa Payload && rm -rf Payload

        artifacts:
            - output/Agrisa.ipa

        publishing:
            email:
                recipients:
                    [
                        nhancd909@gmail.com,
                        hgiap46@gmail.com,
                        laithinh1310@gmail.com,
                    ]
                notify:
                    success: true
                    failure: true
